CREATE TABLE autor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assunto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE livro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(40) NOT NULL,
    editora VARCHAR(40) NOT NULL,
    edicao INTEGER NOT NULL,
    ano_publicacao INTEGER NOT NULL,
    valor NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_livro_edicao_positive CHECK (edicao > 0),
    CONSTRAINT ck_livro_ano_publicacao CHECK (ano_publicacao BETWEEN 1000 AND 9999),
    CONSTRAINT ck_livro_valor_non_negative CHECK (valor >= 0)
);

CREATE TABLE livro_autor (
    livro_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    PRIMARY KEY (livro_id, autor_id),
    CONSTRAINT fk_livro_autor_livro FOREIGN KEY (livro_id) REFERENCES livro(id) ON DELETE RESTRICT,
    CONSTRAINT fk_livro_autor_autor FOREIGN KEY (autor_id) REFERENCES autor(id) ON DELETE RESTRICT
);

CREATE TABLE livro_assunto (
    livro_id BIGINT NOT NULL,
    assunto_id BIGINT NOT NULL,
    PRIMARY KEY (livro_id, assunto_id),
    CONSTRAINT fk_livro_assunto_livro FOREIGN KEY (livro_id) REFERENCES livro(id) ON DELETE RESTRICT,
    CONSTRAINT fk_livro_assunto_assunto FOREIGN KEY (assunto_id) REFERENCES assunto(id) ON DELETE RESTRICT
);

CREATE INDEX idx_autor_nome ON autor (nome);
CREATE INDEX idx_assunto_descricao ON assunto (descricao);
CREATE INDEX idx_livro_titulo ON livro (titulo);
CREATE INDEX idx_livro_autor_autor_id ON livro_autor (autor_id);
CREATE INDEX idx_livro_assunto_assunto_id ON livro_assunto (assunto_id);

CREATE VIEW vw_relatorio_livros_por_autor AS
SELECT
    a.id AS autor_id,
    a.nome AS autor_nome,
    l.id AS livro_id,
    l.titulo AS livro_titulo,
    l.editora AS editora,
    l.edicao AS edicao,
    l.ano_publicacao AS ano_publicacao,
    l.valor AS valor,
    s.id AS assunto_id,
    s.descricao AS assunto_descricao
FROM livro l
JOIN livro_autor la ON la.livro_id = l.id
JOIN autor a ON a.id = la.autor_id
JOIN livro_assunto ls ON ls.livro_id = l.id
JOIN assunto s ON s.id = ls.assunto_id;
